spring.application.name=fipeDataIngestion

# URL do serviço FIPE
fipe.url=https://fipe.parallelum.com.br/api/v2/

# Configuração do Kafka
spring.broker.server=kafka:9092

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do servidor Spring Boot
server.port=8082
